apiVersion: apps/v1
kind: Deployment
metadata:
  name: myreplicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: site
        image: meseque/conversao-temperatura:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-page
spec:
  selector:
    app: web
  ports:
    - port: 80
      protocol: TCP
      nodePort: 30000
  type: NodePort   